### ISSUE TITLE
Add support for context nodes

### ISSUE THREAD

**Issue by elazar** [zendframework/zend-dom#2]
[`DOMXPath->query()`](http://php.net/manual/en/domxpath.query.php) has a second parameter, `$contextNode`, that supports querying in the context of a specific node rather than relative to the document root. It would be nice if `Zend\Dom\Query->queryXPath()` provided equivalent support.

If the maintainers agree that it's reasonable to add this feature, I'd be happy to submit a PR that implements it. If so, any specifics on preferences regarding that implementation would be appreciated.

**Comment by weierophinney** [comment]
@elazar GO FOR EEEETTTTT! :)
